version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000-5002:5000-5002
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=thisisasecret
    ports:
      - 1433:1433
    volumes:
      - database-data:/var/opt/mssql/data
volumes:
  database-data:
