version: "3.9"
services:
  app:
    image: callmedavid/scheduler
    ports:
      - 5001:80
      - 443:443
    depends_on:
      - database
    command: ["dotnet", "ef", "database update"]
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Thisisasecret6969"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
volumes:
  data:
