version: "3.9"
services:
  app:
    image: callmedavid/scheduler
    ports:
      - 5001:80
      - 443:443
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Thisisasecret6969"
      ACCEPT_EULA: "Y"
    ports:
      - 5004:1433
    volumes:
      - database-data:/var/opt/mssql/data
volumes:
  data:
