version: "3.9"
services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    ports:
      - 5003:80
      - 443:443
    depends_on:
      - database

  sdk:
    build:
      context: .
      dockerfile: Dockerfile.sdk
    ports:
      - 5005:5000
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Thisisasecret6969"
      ACCEPT_EULA: "Y"
    ports:
      - 5004:1433
    volumes:
      - ./data:/var/opt/mssql/data
