version: "3.9"
services:
  app:
    build: 
      context: .
    ports:
      - 5001:80
      - 443:443
    depends_on:
      - database
    command: ["dotnet", "ef", "database update"]
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Thisisasecret6969"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 5004:1433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
