version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    container_name: app
    ports:
      - 5003:80
      - 443:443
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server
    user: root
    environment:
      SA_PASSWORD: "Thisisasecret6969"
      ACCEPT_EULA: "Y"
    ports:
      - 5004:1433
    volumes:
      - ./mssql/data:/var/opt/mssql/data