name: Telegram Notification
description: Send a Telegram notification after push
author: Blue-phesant

inputs:
  recipients:
    description: 'Recipients of the notification (comma-separated)'
    required: true
  telegram_token:
    description: 'Telegram Bot Token'
    required: true
  message:
    description: 'Notification message'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
  pre:
    steps:
      - name: Install Dependencies
        run: npm install
