name: Send Telegram Message
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        run: |
          npm run send-telegram-message -- \
            --token $TELEGRAM_TOKEN \
            --to $TELEGRAM_TO \
            --message |
              echo "**New Commit Pushed**"
              echo "Repository: ${{ github.repository }}"
              echo "Branch: ${{ github.ref }}"
              echo "Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
              echo "Author: ${{ github.actor }}"

