name: Telegram Notification

on:
  push:
    branches: [master]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Telegram Notification
        uses: ./.github/actions/telegram-notification
        with:
          recipients: ${{ secrets.TELEGRAM_TO }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **New Commit Pushed**
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            Author: ${{ github.actor }}
